algoritmo "Exercicio14_Faccat"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :  Jailson
// Descrição   :  Verificar se é Positivo ou Negativo
// Autor(a)    : Douglas Tanan Rodrigues
// Data atual  : 18/03/2025
var
    valor: real
inicio
    escreva("Digite um valor: ")
    leia(valor)

    se valor >10 então
        escreva("O valor é maior que 10!")
    senao
        escreva("O valor é menor que 10!")
    fimse
fimalgoritmo
