algoritmo "Divisíveis por 4 menores que 200"
// Disciplina   : Lógica de Programação com VisualG
// Professor    : Jailson
// Descrição    : Programa que apresenta os números divisíveis por 4 menores que 200
// Autor(a)     : Douglas Tanan Rodrigues
// Data atual   : 08/04/2025

var
   numero: inteiro

inicio
   para numero de 1 ate 199 faca
      se numero % 4 = 0 entao
         escreval(numero)
      fimse
   fimpara
fimalgoritmo
