algoritmo "Somatório dos valores de 1 até 500"
// Disciplina   : Lógica de Programação com VisualG
// Professor    : Jailson
// Descrição    : Programa que apresenta o somatório dos valores de 1 até 500
// Autor(a)     : Douglas Tanan Rodrigues
// Data atual   : 08/04/2025

var
   numero, soma: inteiro

inicio
   soma <- 0
   para numero de 1 ate 500 faca
      soma <- soma + numero
   fimpara
   escreval("O somatório dos valores de 1 até 500 é: ", soma)
fimalgoritmo
