algoritmo "exercicio_k"
// Disciplina   : [Lógica de Programação com visualg]
// Professor    : Jailson
// Descrição    : Programa que verifica se número não é maior que 3
// Autor(a)     : Douglas Tanan Rodrigues
// Data atual   : 08/04/2025

var
   numero: inteiro

inicio
   escreva("Digite um número inteiro: ")
   leia(numero)

   se numero <= 3 entao
      escreval("Número informado: ", numero)
   fimse
fimalgoritmo
