algoritmo "impares_de_0_a_20"

// Disciplina   : [Lógica de Programação com visualg]
// Professor    : Jailson
// Descrição    : Programa que apresenta os números ímpares de 0 a 20
// Autor(a)     : Douglas Tanan Rodrigues
// Data atual   : 08/04/2025

var
   numero : inteiro

inicio
   para numero de 0 ate 20 faca
      se (numero % 2 <> 0) entao
         escreval(numero)
      fimse
   fimpara
fimalgoritmo
