algoritmo "exercicio_i"
// Disciplina   : [Lógica de Programação com visualg]
// Professor    : Jailson
// Descrição    : Programa que verifica se o número é par ou ímpar
// Autor(a)     : Douglas Tanan Rodrigues
// Data atual   : 08/04/2025

var
   numero: inteiro

inicio
   escreva("Digite um número inteiro: ")
   leia(numero)

   se numero mod 2 = 0 entao
      escreval("O número é par.")
   senao
      escreval("O número é ímpar.")
   fimse
fimalgoritmo
