algoritmo "divisiveis_por_4_ate_200"
// Disciplina   : [Lógica de Programação com visualg]
// Professor    : Jailson
// Descrição    : Mostrar números divisíveis por 4 menores que 200
// Autor(a)     : Douglas Tanan Rodrigues
// Data atual   : 08/04/2025

var
   numero: inteiro

inicio
   para numero de 1 ate 199 faca
      se numero % 4 = 0 entao
         escreval(numero, " é divisível por 4")
      fimse
   fimpara
fimalgoritmo
