algoritmo "Quadrados de 15 a 200"
// Disciplina   : [Lógica de Programação com visualg]
// Professor    : Jailson
// Descrição    : Programa que apresenta os quadrados dos números inteiros de 15 a 200
// Autor(a)     : Douglas Tanan Rodrigues
// Data atual   : 08/04/2025

var
   numero: inteiro

inicio
   para numero de 15 ate 200 faca
      escreval("Número: ", numero, " - Quadrado: ", numero * numero)
   fimpara
fimalgoritmo
